/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelcutter.gui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import modelcutter.Model;

/**
 *
 * @author MICHAL
 */
public class ExportingDialogPanel extends javax.swing.JPanel {

    private Models3dExportingTableModel tableModel;
    private List<Model> modelsToSave;
    
    /**
     * Creates new form SavingDialogPanel
     */
    public ExportingDialogPanel() {
        initComponents();
    }
    
    public ExportingDialogPanel(List<Model> models){
        initComponents();
        this.tableModel = (Models3dExportingTableModel) modelsTable.getModel();
        this.tableModel.addModels3d(models);
        this.modelsToSave = models;
    }
    
    public List<Model> getAllSelectedModels(){
        List<Model> selectedModels = new ArrayList<>();
        
        for(int i = 0; i < this.modelsToSave.size(); i++){
            if((Boolean) this.modelsTable.getValueAt(i, 2)){
                selectedModels.add(this.modelsToSave.get(i));
            }
        }
        
        return selectedModels;
    }
    
    public boolean exportToASCII(){
        String selectedFormat = (String) formatComboBox.getSelectedItem(); 
        
        return selectedFormat.equals("ASCII");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelsTable = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        formatComboBox = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(390, 320));

        modelsTable.setModel(new modelcutter.gui.Models3dExportingTableModel());
        modelsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        modelsTable.setDefaultRenderer(Color.class, new ColorCellRenderer());
        TableCellRenderer headerRenderer = modelsTable.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) headerRenderer;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        modelsTable.setDefaultRenderer(String.class, centerRenderer);

        modelsTable.getColumnModel().getColumn(0).setMinWidth(15);
        modelsTable.getColumnModel().getColumn(0).setMaxWidth(15);
        modelsTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        jScrollPane1.setViewportView(modelsTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        textLabel.setText("Export selected models in :");

        formatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASCII", "Binary" }));

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(textLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel)
                    .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JComboBox formatComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable modelsTable;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
